import type { Metadata } from "next";
import { Poppins } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
// import { cn } from "@/lib/utils";
import NextAuthProvider from './../Providers/Components/nextauth.providers';
import { ToastContainer } from 'react-toastify';
import 'react-toastify/dist/ReactToastify.css';



const Font = Poppins({
  subsets: ["latin"],
  weight: ["400"]
});


export const metadata: Metadata = {
  title: "Mentra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={Font.className}>
      <body
        className={`${Font.className} antialiased`}
      >

        <div>
          <NextAuthProvider>
            <Navbar />
            <div >

              {children}
            </div>
          </NextAuthProvider>

        </div>

        <ToastContainer position="top-center" autoClose={3000} />

      </body>
    </html>
  );
}
