import type { Metadata } from "next";
import { Poppins, Geist } from "next/font/google";
import "./globals.css";
import Navbar from "./_components/Navbar";
import Footer from "./_components/Footer";
import { cn } from "@/lib/utils";

const geist = Geist({subsets:['latin'],variable:'--font-sans'});

const Font = Poppins({
  subsets: ["latin"],
  weight: ["400"]
});


export const metadata: Metadata = {
  title: "Mentra",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={cn("font-sans", geist.variable)}>
      <body
        className={`${Font.className} antialiased`}
      >

        <div>
          <Navbar />
          <div >
            {children}
          </div>

        </div>

      </body>
    </html>
  );
}
